"""update activity table

Revision ID: e5b95e92e17c
Revises: e270d662007c
Create Date: 2025-08-10 18:53:58.456267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b95e92e17c'
down_revision: Union[str, Sequence[str], None] = 'e270d662007c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activities_parent_id_fkey'), 'activities', type_='foreignkey')
    op.drop_column('activities', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('activities_parent_id_fkey'), 'activities', 'activities', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
