"""update tables fields

Revision ID: e82637279c6e
Revises: e5b95e92e17c
Create Date: 2025-08-11 02:38:30.728136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82637279c6e'
down_revision: Union[str, Sequence[str], None] = 'e5b95e92e17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'activities', ['name'])
    op.create_index(op.f('ix_phones_phone'), 'phones', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phones_phone'), table_name='phones')
    op.drop_constraint(None, 'activities', type_='unique')
    # ### end Alembic commands ###
